### ISSUE TITLE
Supports choosing NodeJS version?

### ISSUE THREAD

**Issue by cheahkhing** [audstanley/NodeJs-Raspberry-Pi#13]
Hi, first of all, i would like to thank you for your great script! 👍 

I am just curious do you think it can support choosing a specific version of NodeJS that's being provided by user?

Like, for now i am getting version9 by default, i would like to choose version8 of NodeJS instead.

**Comment by audstanley** [comment]
Thank you so much. :-)

I have been thinking about doing this for quite a while, so yes.  This is going to be one of my summer projects, and I'm likely going to write it in python.

**Comment by audstanley** [comment]
You will need to re-run the shell script, and then you should be able to run the node-install system wide installer.  Thanks for pushing me to do this.
