### ISSUE TITLE
Fails on RPi 3 B+ with fresh install of Raspbian Stretch Lite

### ISSUE THREAD

**Issue by kryten87** [audstanley/NodeJs-Raspberry-Pi#16]
Here's what it looks like:

    Updating Repositories...
    Need to install some dependencies, this may take a few minutes...
    Installing Python Pip...
    Installing Python Requests Library...
    Traceback (most recent call last):
      File "/bin/node-install", line 241, in <module>
        installDependencies()
      File "/bin/node-install", line 68, in installDependencies
        o, e = Popen(['pip', 'install', 'requests'], stdout=PIPE, stderr=PIPE).communicate()
      File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

The problem is that the "Installing Python Pip..." step failed silently. The `node-install` script attempts to install `python2-pip`, but in Raspbian Stretch lite that package is called `python-pip`.

**Comment by audstanley** [comment]
Thank you so much for the update.  I'll test this out in the next few days.

**Comment by JadedBlueEyes** [comment]
still getting a similar error. see my issue.

**Comment by audstanley** [comment]
Thank you both.  I annoyingly didn't have the issue, so I'm going to run a fresh install again (i had run the desktop upgrade, and everything worked fine).  Hopefully i can replicate the problem.

**Comment by audstanley** [comment]
... oh, and i didn't flash LITE, i flashed desktop ${face palm}

**Comment by audstanley** [comment]
Ok, perfect. python2-pip was the issue.  It's been changed, and works great now.  Thank you again for the report

**Comment by TomlinscoteDeveloper** [comment]
Thanks! 😄

**Comment by JadedBlueEyes** [comment]
Thanks 😄

**Comment by audstanley** [comment]
oh course... and yeah it looks like raspbian stretch desktop came with requests, which i didn't expect.  I don't think Jessy came with it, so that's kinda cool.

...and thank you for the catch.  It saved me a lot of time to get straight to the issue.  😄
