### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by caseydierking** [audstanley/NodeJs-Raspberry-Pi#19]
Tried your script but I'm getting a 404.

--2019-04-09 23:02:20--  https://nodejs.org/dist/latest-v10.x/node-v11.13.0-linux-armv6l.tar.gz
Resolving nodejs.org (nodejs.org)... 104.20.23.46, 104.20.22.46, 2606:4700:10::6814:172e, ...
Connecting to nodejs.org (nodejs.org)|104.20.23.46|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-09 23:02:21 ERROR 404: Not Found.

tar (child): node-v11.13.0-linux-armv6l.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'node-v11.13.0-linux-armv6l.tar.gz': No such file or directory
mv: cannot stat '/root/tempNode/node-v11.13.0-linux-armv6l/': No such file or directory
update-alternatives: error: alternative path /opt/nodejs/bin/node doesn't exist
update-alternatives: error: alternative path /opt/nodejs/bin/npm doesn't exist
--2019-04-09 23:02:21--  https://raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/node-install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.184.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.184.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10841 (11K) [text/plain]
Saving to: ‘node-install’

**Comment by axsb** [comment]
just change line 11
`cd ~/ && mkdir tempNode && cd tempNode && wget https://nodejs.org/dist/latest-v10.x/$LINKTONODE;`
to
`cd ~/ && mkdir tempNode && cd tempNode && wget https://nodejs.org/dist/latest-v11.x/$LINKTONODE;`

**Comment by zackdvd** [comment]
Can confirm that. Thank you.

**Comment by audstanley** [comment]
oh man, thank you.  fixed.
