### ISSUE TITLE
node-install does not install node(

### ISSUE THREAD

**Issue by Andrysky** [audstanley/NodeJs-Raspberry-Pi#22]
pi@rpi:~ $ sudo node-install -v 12;
                                  ;               
                                  +++             
                                  +++             
                                  +++             
   ''++''       :;;',        ,+++;+++    ''++''   
:++++++++++: ;;;;;;;''''  '++++'+++++ :++++++++++:
+++.    .++' ';;;;;;;;''  +++     +++ '++. '' .+++
+++.    .++' '';;;;;;;;'  +++     +++ '++. '' ''  
+++.    .++' ''';;;;;;;;  '++++'+++++ :+++++,     
:          ,   '';;;,        ,+++;       ''++'.   
                   #+''#';+''+'                   
                   ';;;+#'+;;'                    
                    .###''@#@                     
                    '@++@@'+#@                    
                  :'@'''@'''''+                   
                   ##@@'''#@+#@                   
                   .'''#''@''#                    
                     '#'''#'                      

Select from list to install specific version of Node 12.X.X:
1.	12.5.0
2.	12.4.0
3.	12.3.1
4.	12.3.0
5.	12.2.0
6.	12.1.0
7.	12.0.0
Selection: 1
Creating, and Changing into directory:/tempNode-12.5.0
Downloading: https://nodejs.org/dist/v12.5.0/node-v12.5.0-linux-armv6l.tar.gz
Extracting: node-v12.5.0-linux-armv6l.tar.gz
Installation is Complete.
pi@rpi:~ $ nodejs -v
-bash: nodejs: command not found

why it does not work (

**Comment by Andrysky** [comment]
https://nodejs.org/dist/v12.5.0/node-v12.5.0-linux-armv6l.tar.gz

404: Page could not be found
ENOENT: no such file or directory

wtf(

**Comment by Andrysky** [comment]
ok sorry well I saw the information in readme
maybe you shouldn't write
Extracting: node-v12.5.0-linux-armv6l.tar.gz - if there is no file
and
Installation is Complete. - if the installation is not made?)

**Comment by audstanley** [comment]
The only reason I have yet to change the code is because I was hoping that they would make builds for ARM6, but It's looking like I'm going to have to just make a condition that if you are running an ARM6, that the shell script just runs node-install -v 11.  If you want to clone and make the change to the shell script, that would be awesome.  :-)

**Comment by audstanley** [comment]
Ok, that should do it. [6a5e5614e3dbe337d75e1bb076db43e051c7dcf6](https://github.com/audstanley/NodeJs-Raspberry-Pi/commit/6a5e5614e3dbe337d75e1bb076db43e051c7dcf6)
