### ISSUE TITLE
Not working in Rasbian Buster

### ISSUE THREAD

**Issue by ryancasler** [audstanley/NodeJs-Raspberry-Pi#25]
Receiving the following error on running the install script.

./Install-Node.sh: line 13: syntax error near unexpected token `else'
./Install-Node.sh: line 13: `else /bin/node-install -a;'

**Comment by audstanley** [comment]
Thank you, I think the lastest merge took care of this.  I'll test the update on my pi 4 soon, or if you get a chance to run the new update l (as of today) and it works, I can close this issue. 🙂

**Comment by ryancasler** [comment]
Thanks!  I will give it a shot later today.

**Comment by audstanley** [comment]
Closing the issue.  There is a new binary released.
