### ISSUE TITLE
Node.js v12 & v13 ARMv6 binaries for the Raspberry Pi Zero or 1

### ISSUE THREAD

**Issue by fivdi** [audstanley/NodeJs-Raspberry-Pi#26]
In the readme is says:

> Please note that there is currently no arm6 build for node version 12 or 13, so you will get prompted to install the latest build of Node v11 if you are installing on a pi zero, or pi 1

Unofficial Node.js v12 & v13 ARMv6 binaries for the Raspberry Pi Zero or 1 are now available at https://unofficial-builds.nodejs.org/download/.

The binaries are provided by the [Node.js unofficial-builds project](https://github.com/nodejs/unofficial-builds/).

NodeJs-Raspberry-Pi could be extended to install these binaries when appropriate. Alternatively, a note could be added to the readme to let people know where the binaries can be found.

**Comment by audstanley** [comment]
Thank you so much.  I'll update the code today! :+1:

**Comment by audstanley** [comment]
It looks like the new binaries are on the official distribution page.  I gave you a thanks in the README for catching this.  Thanks

**Comment by fivdi** [comment]
> It looks like the new binaries are on the official distribution page.

Unfortunately this isn't the case, or at least I can't see the binaries there. For example, `node-v12.14.0-linux-armv6l.tar.gz` which contains the Node.js v12.14.0 ARMv6 binaries for the Raspberry Pi Zero or 1 is available for download at the *unofficial* distribution page here:

>https://unofficial-builds.nodejs.org/download/release/v12.14.0

It's not at available for download at the *official* distribution page here:

> https://nodejs.org/dist/latest-v12.x/

or here:

> https://nodejs.org/dist/v12.14.0/

I'm not familiar with the code base for NodeJs-Raspberry-Pi but I don't think commit f8c8cfc8c12b4d6a4ff7190578ba7d3c5ebc1fc9 will resolve the issue.

**Comment by audstanley** [comment]
Shoot, this is going to require a bit more work, thanks.

**Comment by audstanley** [comment]
Finally got around to fixing it. The new installer will work with the Pi-Zero and the unofficial releases.
