### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by DronNick** [audstanley/NodeJs-Raspberry-Pi#28]
I get following error while installing:

`pi@raspberrypi:~ $ wget -O - https://raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/Install-Node.sh | sudo bash;
--2020-06-09 16:26:39--  https://raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/Install-Node.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 405 [text/plain]
Saving to: ‘STDOUT’

-                                                                               100%[======================================================================================================================================================================================================>]     405  --.-KB/s   in 0s

2020-06-09 16:26:39 (2.42 MB/s) - written to stdout [405/405]

rm: cannot remove ‘node-install’: No such file or directory
--2020-06-09 16:26:39--  https://raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/node-install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10913 (11K) [text/plain]
Saving to: ‘node-install’

node-install                                                                    100%[======================================================================================================================================================================================================>]  10.66K  --.-KB/s   in 0.002s

2020-06-09 16:26:39 (4.28 MB/s) - ‘node-install’ saved [10913/10913]

                                  ;
                                  +++
                                  +++
                                  +++
   ''++''       :;;',        ,+++;+++    ''++''
:++++++++++: ;;;;;;;''''  '++++'+++++ :++++++++++:
+++.    .++' ';;;;;;;;''  +++     +++ '++. '' .+++
+++.    .++' '';;;;;;;;'  +++     +++ '++. '' ''
+++.    .++' ''';;;;;;;;  '++++'+++++ :+++++,
:          ,   '';;;,        ,+++;       ''++'.
                   #+''#';+''+'
                   ';;;+#'+;;'
                    .###''@#@
                    '@++@@'+#@
                  :'@'''@'''''+
                   ##@@'''#@+#@
                   .'''#''@''#
                     '#'''#'

Installing Python Requests Library...
Traceback (most recent call last):
  File "/bin/node-install", line 249, in <module>
    installLatestVersion()
  File "/bin/node-install", line 223, in installLatestVersion
    import requests
ImportError: No module named requests
`

**Comment by audstanley** [comment]
No longer using python and the requests library. Now using GoLang, so this can finally be closed.
