### ISSUE TITLE
Issue in raspberry pi zero w

### ISSUE THREAD

**Issue by solid-droid** [audstanley/NodeJs-Raspberry-Pi#32]
![image](https://user-images.githubusercontent.com/32586986/161842325-f7a80de3-370d-4447-8190-d66ec972d1bd.png)

OS : 2022-01-28-raspios-bullseye-armhf-lite

**Comment by audstanley** [comment]
Thank you, It looks like there just isn't a release for 17.8.0 at the 'unofficial' Node release page for armv6: https://unofficial-builds.nodejs.org/download/release/v17.8.0/

You should be able to install 17.9.0 - I was thinking about having nightly maps of the releases that might not make it to armv6, but that's a lot of work considering the NodeJs team might have a build sooner than I have a chance to apply an update to this code.

I'll leave this issue open for anyone specifically looking to install 17.8.0 on a pi zero (armv6).

#### Suggested:
Install 17.9.0
