### ISSUE TITLE
First install RPI 2

### ISSUE THREAD

**Issue by joaosilvareed** [audstanley/NodeJs-Raspberry-Pi#5]
> ./Install-Node.sh: line 26: /usr/sbin/node: No such file or directory
> ln: missing file operand
> Try 'ln --help' for more information.
> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module '/usr/local/bin/node'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:418:7)
>     at startup (bootstrap_node.js:139:9)
>     at bootstrap_node.js:533:3
> ./Install-Node.sh: line 28: /usr/bin/npm: No such file or directory
> ln: missing file operand
> Try 'ln --help' for more information.

**Comment by audstanley** [comment]
Thank you so much for opening the issue.  I'll look into it today.  Which version of Raspbian are you running?
