### ISSUE TITLE
No arm7 File for v8.1.1

### ISSUE THREAD

**Issue by hmreimers** [audstanley/NodeJs-Raspberry-Pi#7]
Hi, there is no arm7 file on the v8.1.1 release.
I had to change both "https://nodejs.org/dist/latest-v8.x/" URLs to "https://nodejs.org/dist/v8.1.0/"
greets 
Henning

**Comment by audstanley** [comment]
Looks like there was a little bit of lag on NodeJs' distro page, It's up now as 8.1.12.
